[workspace]
members = [
    "examples/parameters",
    "examples/pubsub",
    "examples/serviceclient",
    "rosrust",
    "rosrust_codegen",
]

[patch.crates-io]
"rosrust" = { path = "rosrust" }
"rosrust_codegen" = { path = "rosrust_codegen" }
