[package]
authors = ["Adnan Ademovic <adnanademovic100@gmail.com>"]
description = "Message generation for rosrust"
license = "MIT"
name = "rosrust_codegen"
readme = "../README.md"
repository = "https://github.com/adnanademovic/rosrust"
version = "0.6.4"

[dependencies]
error-chain = "0.11.0"
lazy_static = "1.0.0"
regex = "0.2.3"
rust-crypto = "0.2.36"
